package com.wanhuhealth.rules
import com.wanhuhealth.rules.globals.RuleResult
import com.wanhuhealth.rules.globals.ResResult
import com.wanhuhealth.rules.fact.OrderFact
import com.wanhuhealth.rules.fact.DrugFact
import java.util.Map
import java.util.HashMap
import java.lang.Math;
import org.slf4j.Logger
import java.util.Collections
import com.wanhuhealth.rules.model.CfgOrderDrugRules
import java.util.List
import org.apache.commons.lang3.StringUtils

global Logger logger;
global List<String> agenda;

rule "ruleLog:日志输出文件规则"
    salience 100
    when
    $orderFact:OrderFact()
    then
   System.out.println("year~");

end
