package com.wanhuRule.hl
import com.wanhuhealth.rules.batch.drools.OrderInfoRuleModel
import com.wanhuhealth.rules.batch.drools.DrugInfoRuleModel
import com.wanhuhealth.rules.batch.drools.DiseaseInfoRuleModel
import com.wanhuhealth.rules.batch.drools.ResResult
import com.wanhuhealth.rules.batch.drools.RuleResult

import java.util.ArrayList
import java.util.Collections
import java.util.Comparator
global ResResult resResult;

//HL0012	中成药功效类别重复	商品名为脑心通胶囊	商品名为利脑心胶囊				禁忌	优先扣除处方中总价高的药品



rule "HL0012:中成药功效类别重复"
salience 4989
lock-on-active true
when
    $orderInfo:OrderInfoRuleModel($drugInfoList: drugInfoList)
    $drugInfo: DrugInfoRuleModel(commonName.trim() == "血脂康胶囊" , $theDrugId: drugId, $main: mainIngredients) from $drugInfoList
    $dupList: ArrayList(size > 0) from collect(DrugInfoRuleModel(!omit, commonName == "利脑心胶囊", drugId != $theDrugId) from $drugInfoList)
then
    $dupList.add($drugInfo);
    $dupList = OrderInfoRuleModel.removeZero($dupList);
    for(int index = 1; index < $dupList.size(); index++){
       DrugInfoRuleModel model = (DrugInfoRuleModel) $dupList.get(index);
       RuleResult ruleResult = new RuleResult();
       ruleResult.setRuleCheckObjectType(2);
       ruleResult.setRuleMark("HL0012");
       ruleResult.setRuleNo("中成药功效类别重复");
       ruleResult.setDrugId(model.getDrugId());
       for (DrugInfoRuleModel drugInfoRuleModel : $orderInfo.getDrugInfoList()) {
           if(drugInfoRuleModel.getDrugId() == model.getDrugId()){
               drugInfoRuleModel.setBuyAmount(0.00);
               drugInfoRuleModel.setOmit(true);
           }
       }

       resResult.getRuleResultList().add(ruleResult);
    }
    update($orderInfo)
 end

// HL0013	中成药功效类别重复	商品名为脑心通胶囊	商品名为血塞通软胶囊				禁忌	优先扣除处方中总价高的药品

rule "HL0013:中成药功效类别重复"
salience 4989
lock-on-active true
when
    $orderInfo:OrderInfoRuleModel($drugInfoList: drugInfoList)
    $drugInfo: DrugInfoRuleModel(commonName.trim() == "血脂康胶囊" , $theDrugId: drugId, $main: mainIngredients) from $drugInfoList
    $dupList: ArrayList(size > 0) from collect(DrugInfoRuleModel(!omit, commonName == "血塞通软胶囊", drugId != $theDrugId) from $drugInfoList)
then
    $dupList.add($drugInfo);
    $dupList = OrderInfoRuleModel.removeZero($dupList);
    for(int index = 1; index < $dupList.size(); index++){
       DrugInfoRuleModel model = (DrugInfoRuleModel) $dupList.get(index);
       RuleResult ruleResult = new RuleResult();
       ruleResult.setRuleCheckObjectType(2);
       ruleResult.setRuleMark("HL0013");
       ruleResult.setRuleNo("中成药功效类别重复");
       ruleResult.setDrugId(model.getDrugId());
       for (DrugInfoRuleModel drugInfoRuleModel : $orderInfo.getDrugInfoList()) {
           if(drugInfoRuleModel.getDrugId() == model.getDrugId()){
               drugInfoRuleModel.setBuyAmount(0.00);
               drugInfoRuleModel.setOmit(true);
           }
       }

       resResult.getRuleResultList().add(ruleResult);
    }
    update($orderInfo)
 end


