package com.wanhuRule.hl
import com.wanhuhealth.rules.batch.drools.OrderInfoRuleModel
import com.wanhuhealth.rules.batch.drools.DrugInfoRuleModel
import com.wanhuhealth.rules.batch.drools.DiseaseInfoRuleModel
import com.wanhuhealth.rules.batch.drools.ResResult
import com.wanhuhealth.rules.batch.drools.RuleResult

import java.util.ArrayList
import java.util.Collections
import java.util.Comparator
global ResResult resResult;

// HL0006	西药主要成分重复	类别1为西药的药品	"1.类别1为西药的药品2.类别7（主要成分）与条件1的药品相同"				禁忌	优先扣除处方中总价高的药品

rule "HL0006:西药主要成分重复"
salience 4995
lock-on-active true
when
    $orderInfo:OrderInfoRuleModel($drugInfoList: drugInfoList)
    $drugInfo: DrugInfoRuleModel($mainIngredient: mainIngredients, $theDrugId: drugId) from $drugInfoList
    $dupList: ArrayList(size > 1) from collect(DrugInfoRuleModel(!omit, firstCategory == "西药", drugId != $theDrugId, !Collections.disjoint($mainIngredient, mainIngredients)) from $drugInfoList)
then
    $dupList.add($drugInfo);
    Collections.sort($dupList, new Comparator<DrugInfoRuleModel>(){
       public int compare(DrugInfoRuleModel arg0, DrugInfoRuleModel arg1) {
           Double d0 = arg0.getBuyAmount() * arg0.getPrice();
           Double d1 = arg1.getBuyAmount() * arg1.getPrice();
                      return d0.compareTo(d1);
                  }
    });
    int eleNumber = 0;
    for(int ins = 0; ins < $dupList.size(); ins++){
       if(!((DrugInfoRuleModel)$dupList.get(ins)).isOmit()){
           eleNumber = ins;
           break;
       }
    }
    for(int index = (1 + eleNumber); index < $dupList.size(); index++){
       DrugInfoRuleModel model = (DrugInfoRuleModel) $dupList.get(index);
       RuleResult ruleResult = new RuleResult();
       ruleResult.setRuleCheckObjectType(2);
       ruleResult.setRuleMark("HL0006");
       ruleResult.setRuleNo("西药主要成分重复");
       ruleResult.setDrugId(model.getDrugId());
       for (DrugInfoRuleModel drugInfoRuleModel : $orderInfo.getDrugInfoList()) {
           if(drugInfoRuleModel.getDrugId() == model.getDrugId()){
               drugInfoRuleModel.setBuyAmount(0.00);
               drugInfoRuleModel.setOmit(true);
           }
       }

       resResult.getRuleResultList().add(ruleResult);
    }
    update($orderInfo)
 end