package com.wanhuRule.hl
import com.wanhuhealth.rules.batch.drools.OrderInfoRuleModel
import com.wanhuhealth.rules.batch.drools.DrugInfoRuleModel
import com.wanhuhealth.rules.batch.drools.DiseaseInfoRuleModel
import com.wanhuhealth.rules.batch.drools.ResResult
import com.wanhuhealth.rules.batch.drools.RuleResult
import java.util.ArrayList
import java.util.Collections
import java.util.Comparator
import com.wanhuhealth.rules.batch.drools.RulesCheckTypeEnum
global ResResult resResult;

//HL0003	合并症用药不合理	诊断中含有高血压+糖尿病+哮喘	类别5β受体阻滞剂的药品				禁忌	扣除此药品
rule "HL0003:合并症用药不合理"
salience 4998
lock-on-active true
when
    $orderInfo:OrderInfoRuleModel(diseaseInfoList contains "高血压" && diseaseInfoList contains "糖尿病" && diseaseInfoList contains "哮喘", $drugInfoList: drugInfoList)
    $drugInfo: DrugInfoRuleModel(!omit, otherCategory contains "β受体阻滞剂") from $drugInfoList
then


    RuleResult ruleResult = new RuleResult();
    ruleResult.setRuleCheckObjectType(RulesCheckTypeEnum.RULE_DRUG.getIndex());
    ruleResult.setMessage("HL0003:合并症用药不合理");
    ruleResult.setRuleMark("HL0003");
    ruleResult.setRuleNo("合并症用药不合理");
    ruleResult.setDrugId($drugInfo.getDrugId());
    $drugInfo.setOmit(true);
    resResult.getRuleResultList().add(ruleResult);

    update($orderInfo);
 end

 //HL0004	合并症用药不合理	诊断中含有高血压+痛风发作期	类别5为利尿剂的药品				禁忌	扣除此药品
 rule "HL0004:合并症用药不合理"
 salience 4997
 lock-on-active true
 when
     $orderInfo:OrderInfoRuleModel(diseaseInfoList contains "高血压" && diseaseInfoList contains "痛风发作期" , $drugInfoList: drugInfoList)
     $drugInfo: DrugInfoRuleModel(!omit, otherCategory contains "利尿剂") from $drugInfoList
 then


     RuleResult ruleResult = new RuleResult();
     ruleResult.setRuleCheckObjectType(RulesCheckTypeEnum.RULE_DRUG.getIndex());
     ruleResult.setMessage("HL0004:合并症用药不合理");
     ruleResult.setRuleMark("HL0004");
     ruleResult.setRuleNo("合并症用药不合理");
     ruleResult.setDrugId($drugInfo.getDrugId());
     $drugInfo.setOmit(true);
     resResult.getRuleResultList().add(ruleResult);

     update($orderInfo);
  end

//HL0005	合并症用药不合理	诊断中含有高血压+高尿酸血症	类别5为利尿剂的药品				禁忌	扣除此药品
rule "HL0005:合并症用药不合理"
salience 4996
lock-on-active true
when
   $orderInfo:OrderInfoRuleModel(diseaseInfoList contains "高血压" && diseaseInfoList contains "高尿酸血症" , $drugInfoList: drugInfoList)
   $drugInfo: DrugInfoRuleModel(!omit, otherCategory contains "利尿剂") from $drugInfoList
then


   RuleResult ruleResult = new RuleResult();
   ruleResult.setRuleCheckObjectType(RulesCheckTypeEnum.RULE_DRUG.getIndex());
   ruleResult.setMessage("HL0005:合并症用药不合理");
   ruleResult.setRuleMark("HL0005");
   ruleResult.setRuleNo("合并症用药不合理");
   ruleResult.setDrugId($drugInfo.getDrugId());
   $drugInfo.setOmit(true);
   resResult.getRuleResultList().add(ruleResult);

   update($orderInfo);
end