package com.clickmed.platform.modules.rules.order
import com.wanhuhealth.rules.batch.drools.RuleResult
import com.wanhuhealth.rules.batch.drools.OrderInfoRuleModel
import com.wanhuhealth.rules.batch.drools.DrugInfoRuleModel
import com.wanhuhealth.rules.batch.drools.DiseaseInfoRuleModel
import com.wanhuhealth.rules.batch.drools.ResResult
import java.util.Map
import java.util.List
import java.util.HashMap
import java.lang.Math
import java.util.ArrayList
import java.util.Collections
import java.util.Comparator;

global ResResult resResult;
salience 97
lock-on-active true
rule "dupGenericName:订单中两个或以上药品通用名相同"
    when
        $orderInfo: OrderInfoRuleModel($drugInfoList:drugInfoList)
           $drugInfo: DrugInfoRuleModel($id:drugId, $theCommonName:commonName) from $drugInfoList
           $dupList: ArrayList(size > 0) from collect( DrugInfoRuleModel(!omit && drugId != $id, commonName == $theCommonName) from $drugInfoList)

    then
            String dupDrugs = "";
            $dupList.add($drugInfo);
            Collections.sort($dupList, new Comparator<DrugInfoRuleModel>(){
               public int compare(DrugInfoRuleModel arg0, DrugInfoRuleModel arg1) {
                   Double d0 = arg0.getBuyAmount() * arg0.getPrice();
                   Double d1 = arg1.getBuyAmount() * arg1.getPrice();
                              return d0.compareTo(d1);
                          }
            });
            int eleNumber = 0;
           for(int ins = 0; ins < $dupList.size(); ins++){
               if(!((DrugInfoRuleModel)$dupList.get(ins)).isOmit()){
                   eleNumber = ins;
                   break;
               }
           }
            for(int index = (1 + eleNumber); index < $dupList.size(); index++){
               DrugInfoRuleModel model = (DrugInfoRuleModel) $dupList.get(index);
               RuleResult ruleResult = new RuleResult();
               ruleResult.setRuleCheckObjectType(2);
               ruleResult.setMessage("同通用名：此药品与" + dupDrugs + "通用名相同，用药重复");
               ruleResult.setRuleMark("dupGenericName");
               ruleResult.setRuleNo("同通用名");
               ruleResult.setDrugId(model.getDrugId());
               for (DrugInfoRuleModel drugInfoRuleModel : $orderInfo.getDrugInfoList()) {
                   if(drugInfoRuleModel.getDrugId() == model.getDrugId()){
                       drugInfoRuleModel.setBuyAmount(0.00);
                       drugInfoRuleModel.setOmit(true);
                   }
               }

               resResult.getRuleResultList().add(ruleResult);
            }
            update($orderInfo)
end
