package com.wanhuRule.hl
import com.wanhuhealth.rules.drools.OrderInfoRuleModel
import com.wanhuhealth.rules.drools.DrugInfoRuleModel
import com.wanhuhealth.rules.drools.DiseaseInfoRuleModel
import com.wanhuhealth.rules.drools.ResResult
import com.wanhuhealth.rules.drools.RuleResult
import com.wanhuhealth.rules.drools.ComputeSalience

import java.util.ArrayList
import java.util.Collections
import java.util.Comparator
global ResResult resResult;
global ComputeSalience computeSalience;

//中成药与西药成分重复	商品名为血脂康胶囊	"1.类别1为西药或西药复方制剂；  2.类别4为他汀类."				禁忌	去掉血脂康胶囊

rule "ChinesePatentWesternDuplicate:中成药与西药成分重复(血脂康－他汀类)"
salience computeSalience.ChinesePatentWesternDuplicate
lock-on-active true
when
    $orderInfo:OrderInfoRuleModel($drugInfoList: drugInfoList)
    $drugInfo: DrugInfoRuleModel(commonName == "血脂康胶囊" , $theDrugId: drugId, $main: mainIngredients) from $drugInfoList
    $dupList: ArrayList(size > 0) from collect(DrugInfoRuleModel(!omit, (firstCategory == "西药" || firstCategory == "西药复方制剂"), drugId != $theDrugId, otherCategory contains "他汀类") from $drugInfoList)
then

    RuleResult ruleResult = new RuleResult();
    ruleResult.setRuleCheckObjectType(2);
    ruleResult.setRuleMark("ChinesePatentWesternDuplicate");
    ruleResult.setMarkName("中成药与西药成分重复(血脂康－他汀类)");
    ruleResult.setDrugId($drugInfo.getDrugId());
    $drugInfo.setBuyAmount(0.00);
    $drugInfo.setOmit(true);
    resResult.getRuleResultList().add(ruleResult);
    update($orderInfo)
 end

