package com.wanhuRule.hl
import com.wanhuhealth.rules.drools.OrderInfoRuleModel
import com.wanhuhealth.rules.drools.DrugInfoRuleModel
import com.wanhuhealth.rules.drools.DiseaseInfoRuleModel
import com.wanhuhealth.rules.drools.ResResult
import com.wanhuhealth.rules.drools.RuleResult
import com.wanhuhealth.rules.drools.ComputeSalience

import java.util.ArrayList
import java.util.Collections
import java.util.Comparator
global ResResult resResult;
global ComputeSalience computeSalience;

//西药药理作用重复	类别1为西药的药品	"1.类别1为西药的药品；  2.类别4与条件1药品类别4相同；3.类别4不为利尿剂。"		禁忌	优先扣除处方中总价高的药品
rule "westernMedicineDuplicate:西药药理作用重复(非利尿剂)"
salience computeSalience.westernMedicineDuplicate
lock-on-active true
when
    $orderInfo:OrderInfoRuleModel($drugInfoList: drugInfoList)
    $drugInfo: DrugInfoRuleModel(firstCategory == "西药" ,$theDrugId: drugId, otherCategory.size > 0, $fifthCategory: otherCategory) from $drugInfoList
    $dupList: ArrayList(size > 0) from collect(DrugInfoRuleModel(!omit, firstCategory == "西药", drugId != $theDrugId, otherCategory.size > 0, $fifthCategory.get(0) ==  otherCategory.get(0), otherCategory.get(0) != "利尿剂") from $drugInfoList)
then
    $dupList.add($drugInfo);
    $dupList = OrderInfoRuleModel.removeZero($dupList);
    for(int index = 1; index < $dupList.size(); index++){
       DrugInfoRuleModel model = (DrugInfoRuleModel) $dupList.get(index);
       RuleResult ruleResult = new RuleResult();
       ruleResult.setRuleCheckObjectType(2);
       ruleResult.setRuleMark("westernMedicineDuplicate");
       ruleResult.setMarkName("西药药理作用重复(非利尿剂)");
       ruleResult.setDrugId(model.getDrugId());
       for (DrugInfoRuleModel drugInfoRuleModel : $orderInfo.getDrugInfoList()) {
           if(drugInfoRuleModel.getDrugId() == model.getDrugId()){
               drugInfoRuleModel.setBuyAmount(0.00);
               drugInfoRuleModel.setOmit(true);
           }
       }

       resResult.getRuleResultList().add(ruleResult);
    }
    update($orderInfo)
 end

 //西药药理作用重复	类别1为西药的药品	"1.类别1为西药的药品；2.类别5与条件1药品类别5相同；   3.类别5不为袢利尿剂、噻嗪类和类噻嗪类利尿剂。"		禁忌	优先扣除处方中总价高的药品

 rule "westernMedicineDuplicate:西药药理作用重复(非袢利尿剂/噻嗪类利尿剂/类噻嗪类利尿剂)"
 salience computeSalience.westernMedicineDuplicate
 lock-on-active true
 when
     $orderInfo:OrderInfoRuleModel($drugInfoList: drugInfoList)
     $drugInfo: DrugInfoRuleModel(firstCategory == "西药" , $theDrugId: drugId, otherCategory.size > 1, $fourth: otherCategory) from $drugInfoList
     $dupList: ArrayList(size > 0) from collect(DrugInfoRuleModel(!omit, firstCategory == "西药", drugId != $theDrugId, otherCategory.get(1) == $fourth.get(1), otherCategory.size > 1, otherCategory.get(1) != "袢利尿剂",otherCategory.get(1) != "噻嗪类",otherCategory.get(1) != "类噻嗪类利尿剂") from $drugInfoList)
 then
     $dupList.add($drugInfo);
     $dupList = OrderInfoRuleModel.removeZero($dupList);
     for(int index = 1; index < $dupList.size(); index++){
        DrugInfoRuleModel model = (DrugInfoRuleModel) $dupList.get(index);
        RuleResult ruleResult = new RuleResult();
        ruleResult.setRuleCheckObjectType(2);
        ruleResult.setRuleMark("westernMedicineDuplicate");
        ruleResult.setMarkName("西药药理作用重复(非袢利尿剂/噻嗪类利尿剂/类噻嗪类利尿剂)");
        ruleResult.setDrugId(model.getDrugId());
        for (DrugInfoRuleModel drugInfoRuleModel : $orderInfo.getDrugInfoList()) {
            if(drugInfoRuleModel.getDrugId() == model.getDrugId()){
                drugInfoRuleModel.setBuyAmount(0.00);
                drugInfoRuleModel.setOmit(true);
            }
        }

        resResult.getRuleResultList().add(ruleResult);
     }
     update($orderInfo)
  end

  //西药药理作用重复	类别1为西药的药品	"1.类别1为西药的药品；    2.类别6与条件1药品类别6相同；    3.类别6不为排钾利尿剂。"		禁忌	优先扣除处方中总价高的药品


   rule "westernMedicineDuplicate:西药药理作用重复(非排钾利尿剂)"
   salience computeSalience.westernMedicineDuplicate
   lock-on-active true
   when
       $orderInfo:OrderInfoRuleModel($drugInfoList: drugInfoList)
       $drugInfo: DrugInfoRuleModel(firstCategory == "西药" , $theDrugId: drugId, otherCategory.size > 2, $sixth: otherCategory) from $drugInfoList
       $dupList: ArrayList(size > 0) from collect(DrugInfoRuleModel(!omit, firstCategory == "西药", drugId != $theDrugId,otherCategory.size > 2,$sixth.get(2) ==  otherCategory.get(2),otherCategory.get(2) != "排钾利尿剂") from $drugInfoList)
   then
       $dupList.add($drugInfo);
       $dupList = OrderInfoRuleModel.removeZero($dupList);
       for(int index = 1; index < $dupList.size(); index++){
          DrugInfoRuleModel model = (DrugInfoRuleModel) $dupList.get(index);
          RuleResult ruleResult = new RuleResult();
          ruleResult.setRuleCheckObjectType(2);
          ruleResult.setRuleMark("westernMedicineDuplicate");
          ruleResult.setMarkName("西药药理作用重复(非排钾利尿剂)");
          ruleResult.setDrugId(model.getDrugId());
          for (DrugInfoRuleModel drugInfoRuleModel : $orderInfo.getDrugInfoList()) {
              if(drugInfoRuleModel.getDrugId() == model.getDrugId()){
                  drugInfoRuleModel.setBuyAmount(0.00);
                  drugInfoRuleModel.setOmit(true);
              }
          }

          resResult.getRuleResultList().add(ruleResult);
       }
       update($orderInfo)
    end

 //西药药理作用重复	类别1为西药的药品	"1.类别1为西药的药品；   2.类别4与条件1药品类别4相同；   3.类别4为利尿剂。"	诊断中含有“心功能不全”或“心力衰竭”或“心衰”或“慢性肾功能不全”或“尿毒症”或“慢性肾衰”	慎用	提示
   rule "westernMedicineDuplicate:西药药理作用重复(特定诊断－利尿剂)"
    salience computeSalience.westernMedicineDuplicate
    lock-on-active true
    when
        $orderInfo:OrderInfoRuleModel($drugInfoList: drugInfoList, (diseaseInfoList contains "心功能不全" || diseaseInfoList contains "心力衰竭" || diseaseInfoList contains "心衰" || diseaseInfoList contains "慢性肾功能不全" || diseaseInfoList contains "尿毒症" || diseaseInfoList contains "慢性肾衰"))
         $drugInfo: DrugInfoRuleModel(firstCategory == "西药" ,$theDrugId: drugId) from $drugInfoList
            $dupList: ArrayList(size > 0) from collect(DrugInfoRuleModel(!omit, firstCategory == "西药", drugId != $theDrugId, otherCategory.size > 0, $fifthCategory: otherCategory.get(0) == "利尿剂") from $drugInfoList)
    then
        // 慎用
        $dupList.add($drugInfo);
        $dupList = OrderInfoRuleModel.removeZero($dupList);
        for(int index = 0; index < $dupList.size(); index++){
           DrugInfoRuleModel model = (DrugInfoRuleModel) $dupList.get(index);
           RuleResult ruleResult = new RuleResult();
           ruleResult.setRuleCheckObjectType(2);
           ruleResult.setRuleMark("westernMedicineDuplicate");
           ruleResult.setMarkName("西药药理作用重复(特定诊断－利尿剂)");
           ruleResult.setDrugId(model.getDrugId());
           /*for (DrugInfoRuleModel drugInfoRuleModel : $orderInfo.getDrugInfoList()) {
               if(drugInfoRuleModel.getDrugId() == model.getDrugId()){
                   drugInfoRuleModel.setBuyAmount(0.00);
                   drugInfoRuleModel.setOmit(true);
               }
           }*/

           resResult.getRuleResultList().add(ruleResult);
        }
        update($orderInfo)
     end

 //西药药理作用重复	类别1为西药的药品	"1.类别1为西药的药品；   2.类别5与条件1药品类别5相同；   3.类别5为袢利尿剂或噻嗪类或类噻嗪类利尿剂。"	诊断中含有“心功能不全”或“心力衰竭”或“心衰”或“慢性肾功能不全”或“尿毒症”或“慢性肾衰”	慎用	提示

   rule "westernMedicineDuplicate:西药药理作用重复(特定诊断－袢利尿剂/噻嗪类利尿剂/类噻嗪类利尿剂)"
    salience computeSalience.westernMedicineDuplicate
    lock-on-active true
    when
        $orderInfo:OrderInfoRuleModel($drugInfoList: drugInfoList, (diseaseInfoList contains "心功能不全" || diseaseInfoList contains "心力衰竭" || diseaseInfoList contains "心衰" || diseaseInfoList contains "慢性肾功能不全" || diseaseInfoList contains "尿毒症" || diseaseInfoList contains "慢性肾衰"))
         $drugInfo: DrugInfoRuleModel(firstCategory == "西药" ,$theDrugId: drugId) from $drugInfoList
            $dupList: ArrayList(size > 0) from collect(DrugInfoRuleModel(!omit, firstCategory == "西药", drugId != $theDrugId, otherCategory.size > 1, (otherCategory.get(1) == "袢利尿剂" || otherCategory.get(1) == "噻嗪类" || otherCategory.get(1) == "类噻嗪类利尿剂" ) ) from $drugInfoList)
    then
        // 慎用
        $dupList.add($drugInfo);
        $dupList = OrderInfoRuleModel.removeZero($dupList);
        for(int index = 0; index < $dupList.size(); index++){
           DrugInfoRuleModel model = (DrugInfoRuleModel) $dupList.get(index);
           RuleResult ruleResult = new RuleResult();
           ruleResult.setRuleCheckObjectType(2);
           ruleResult.setRuleMark("westernMedicineDuplicate");
           ruleResult.setMarkName("西药药理作用重复(特定诊断－袢利尿剂/噻嗪类利尿剂/类噻嗪类利尿剂)");
           ruleResult.setDrugId(model.getDrugId());
           /*for (DrugInfoRuleModel drugInfoRuleModel : $orderInfo.getDrugInfoList()) {
               if(drugInfoRuleModel.getDrugId() == model.getDrugId()){
                   drugInfoRuleModel.setBuyAmount(0.00);
                   drugInfoRuleModel.setOmit(true);
               }
           }*/

           resResult.getRuleResultList().add(ruleResult);
        }
        update($orderInfo)
     end


 //西药药理作用重复	类别1为西药的药品	"1.类别1为西药的药品；   2.类别6与条件1药品类别6相同；   3.类别6为排钾利尿剂。"	诊断中含有“心功能不全”或“心力衰竭”或“心衰”或“慢性肾功能不全”或“尿毒症”或“慢性肾衰”	慎用	提示

 rule "westernMedicineDuplicate:西药药理作用重复(特定诊断－排钾利尿剂)"
    salience computeSalience.westernMedicineDuplicate
    lock-on-active true
    when
        $orderInfo:OrderInfoRuleModel($drugInfoList: drugInfoList, (diseaseInfoList contains "心功能不全" || diseaseInfoList contains "心力衰竭" || diseaseInfoList contains "心衰" || diseaseInfoList contains "慢性肾功能不全" || diseaseInfoList contains "尿毒症" || diseaseInfoList contains "慢性肾衰"))
         $drugInfo: DrugInfoRuleModel(firstCategory == "西药" ,$theDrugId: drugId) from $drugInfoList
            $dupList: ArrayList(size > 0) from collect(DrugInfoRuleModel(!omit, firstCategory == "西药", drugId != $theDrugId, otherCategory.size > 2, otherCategory.get(2) == "排钾利尿剂") from $drugInfoList)
    then
        // 慎用
        $dupList.add($drugInfo);
        $dupList = OrderInfoRuleModel.removeZero($dupList);
        for(int index = 0; index < $dupList.size(); index++){
           DrugInfoRuleModel model = (DrugInfoRuleModel) $dupList.get(index);
           RuleResult ruleResult = new RuleResult();
           ruleResult.setRuleCheckObjectType(2);
           ruleResult.setRuleMark("westernMedicineDuplicate");
           ruleResult.setMarkName("西药药理作用重复(特定诊断－排钾利尿剂)");
           ruleResult.setDrugId(model.getDrugId());
           /*for (DrugInfoRuleModel drugInfoRuleModel : $orderInfo.getDrugInfoList()) {
               if(drugInfoRuleModel.getDrugId() == model.getDrugId()){
                   drugInfoRuleModel.setBuyAmount(0.00);
                   drugInfoRuleModel.setOmit(true);
               }
           }*/

           resResult.getRuleResultList().add(ruleResult);
        }
        update($orderInfo)
     end